// src/lib/components/ChordTooltipContent.svelte
<script lang="ts">
	import type { Match } from '$lib/frontend/types';
	import MatchBadge from './MatchBadge.svelte';
	import ConstraintScores from './ConstraintScores.svelte';

	let {
		match,
		needText,
		capacityText
	}: {
		match: Match;
		needText: string;
		capacityText: string;
	} = $props();

	const catMatch = $derived(match.breakdown.categoryMatch);
	const hasCategory = $derived(catMatch && !catMatch.isBlocked && catMatch.overlapCategory);
</script>

<div>
	<strong>Match</strong>
	{' '}
	<span style="color: #4CAF50">
		{(match.score * 100).toFixed(0)}%
	</span>
	<MatchBadge {match} />
	<div class="match-connection">
		<div class="match-connection-expr">"{needText}"</div>
		<div class="match-connection-link">
			{#if hasCategory && catMatch}
				{#if catMatch.overlapDistance === 0}
					<span class="link-word">{catMatch.overlapCategory}</span>
				{:else}
					<span>both relate to</span>
					<span class="link-word">{catMatch.overlapCategory}</span>
				{/if}
			{:else}
				<span>similar to</span>
			{/if}
		</div>
		<div class="match-connection-expr">"{capacityText}"</div>
	</div>
	<ConstraintScores breakdown={match.breakdown} />
</div>

// src/frontend/components/ChordTooltipContent.tsx
import type { Match } from '../types.ts'
import { MatchBadge } from './MatchBadge.tsx'
import { ConstraintScores } from './ConstraintScores.tsx'

type ChordTooltipContentProps = {
  match: Match
  needText: string
  capacityText: string
}

export function ChordTooltipContent({
  match,
  needText,
  capacityText,
}: ChordTooltipContentProps): React.ReactElement {
  const catMatch = match.breakdown.categoryMatch
  const hasCategory = catMatch && !catMatch.isBlocked && catMatch.overlapCategory

  return (
    <div>
      <strong>Match</strong>{' '}
      <span style={{ color: '#4CAF50' }}>
        {(match.score * 100).toFixed(0)}%
      </span>
      <MatchBadge match={match} />
      <div className="match-connection">
        <div className="match-connection-expr">"{needText}"</div>
        <div className="match-connection-link">
          {hasCategory ? (
            catMatch.overlapDistance === 0 ? (
              <span className="link-word">{catMatch.overlapCategory}</span>
            ) : (
              <>
                <span>both relate to</span>
                <span className="link-word">{catMatch.overlapCategory}</span>
              </>
            )
          ) : (
            <span>similar to</span>
          )}
        </div>
        <div className="match-connection-expr">"{capacityText}"</div>
      </div>
      <ConstraintScores breakdown={match.breakdown} />
    </div>
  )
}
