// svelte/src/lib/components/ItemCard.svelte
<script lang="ts">
	import type { PCATransform } from '$lib/core/semantic-colors';
	import type { NodeItem } from '$lib/frontend/types';
	import { getNodeColor } from '$lib/frontend/utils';
	import type { Snippet } from 'svelte';

	let {
		item,
		isCapacity,
		transform,
		score,
		children
	}: {
		item: NodeItem;
		isCapacity: boolean;
		transform: PCATransform;
		score?: number;
		children?: Snippet;
	} = $props();

	const color = $derived(getNodeColor(item.embedding, transform, isCapacity));
</script>

<div class="match-item">
	<div class="match-item-header">
		<div style="display: flex; align-items: center; gap: 6px;">
			<div
				class="node-header-icon {isCapacity ? 'capacity' : ''}"
				style="background: {color}; width: 12px; height: 12px;"
			></div>
			<span>{item.label}</span>
		</div>
		{#if score !== undefined}
			<span class="match-item-score">
				{(score * 100).toFixed(0)}%
			</span>
		{/if}
	</div>
	<div style="font-size: 0.8em; color: #888; margin-top: 2px;">
		{isCapacity ? 'Capacity' : 'Need'}
	</div>
	{#if children}
		{@render children()}
	{/if}
</div>

// src/frontend/components/ItemCard.tsx
import type { PCATransform } from '../../semantic-colors.ts'
import type { NodeItem } from '../types.ts'
import { getNodeColor } from '../utils.ts'

type ItemCardProps = {
  item: NodeItem
  isCapacity: boolean
  transform: PCATransform
  score?: number
  children?: React.ReactNode
}

export function ItemCard({ item, isCapacity, transform, score, children }: ItemCardProps): React.ReactElement {
  const color = getNodeColor(item.embedding, transform, isCapacity)

  return (
    <div className="match-item">
      <div className="match-item-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <div
            className={`node-header-icon ${isCapacity ? 'capacity' : ''}`}
            style={{ background: color, width: 12, height: 12 }}
          />
          <span>{item.label}</span>
        </div>
        {score !== undefined && (
          <span className="match-item-score">
            {(score * 100).toFixed(0)}%
          </span>
        )}
      </div>
      <div style={{ fontSize: '0.8em', color: '#888', marginTop: 2 }}>
        {isCapacity ? 'Capacity' : 'Need'}
      </div>
      {children}
    </div>
  )
}
