// svelte/src/lib/components/NodeTooltipContent.svelte
<script lang="ts">
	import type { NodeItem } from '$lib/frontend/types';

	let {
		item,
		isCapacity,
		color
	}: {
		item: NodeItem;
		isCapacity: boolean;
		color: string;
	} = $props();
</script>

<div>
	<strong style="color: {color}">
		{isCapacity ? 'Capacity' : 'Need'} #{item.id}
	</strong>
	<br />
	{item.label}
</div>

// src/frontend/components/NodeTooltipContent.tsx
import type { NodeItem } from '../types.ts'

type NodeTooltipContentProps = {
  item: NodeItem
  isCapacity: boolean
  color: string
}

export function NodeTooltipContent({
  item,
  isCapacity,
  color,
}: NodeTooltipContentProps): React.ReactElement {
  return (
    <div>
      <strong style={{ color }}>
        {isCapacity ? 'Capacity' : 'Need'} #{item.id}
      </strong>
      <br />
      {item.label}
    </div>
  )
}
