// src/frontend/components/MatchBadge.tsx
import type { Match } from '../types.ts'

export function MatchBadge({ match }: { match: Match }): React.ReactElement {
  const cat = match.breakdown.categoryMatch

  if (cat && !cat.isBlocked && cat.overlapCategory) {
    if (cat.overlapDistance === 0) {
      return (
        <span className="match-level-badge match-level-exact">
          Both: {cat.overlapCategory}
        </span>
      )
    }
    return (
      <span className="match-level-badge match-level-related">
        Via: {cat.overlapCategory}
      </span>
    )
  }

  return (
    <span className="match-level-badge match-level-embedding">
      Similar meaning
    </span>
  )
}

// svelte/src/lib/components/MatchBadge.svelte
<script lang="ts">
	import type { Match } from '$lib/frontend/types';

	let { match }: { match: Match } = $props();

	const cat = $derived(match.breakdown.categoryMatch);
	const hasCat = $derived(cat && !cat.isBlocked && cat.overlapCategory);
</script>

{#if hasCat && cat}
	{#if cat.overlapDistance === 0}
		<span class="match-level-badge match-level-exact">Both: {cat.overlapCategory}</span>
	{:else}
		<span class="match-level-badge match-level-related">Via: {cat.overlapCategory}</span>
	{/if}
{:else}
	<span class="match-level-badge match-level-embedding">Similar meaning</span>
{/if}
